/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScriptsIndexRouteImport } from './routes/scripts.index'
import { Route as PrompterIndexRouteImport } from './routes/prompter.index'
import { Route as ScriptsNewRouteImport } from './routes/scripts.new'
import { Route as ScriptsIdRouteImport } from './routes/scripts.$id'
import { Route as PrompterIdRouteImport } from './routes/prompter.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsIndexRoute = ScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrompterIndexRoute = PrompterIndexRouteImport.update({
  id: '/prompter/',
  path: '/prompter/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsNewRoute = ScriptsNewRouteImport.update({
  id: '/scripts/new',
  path: '/scripts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsIdRoute = ScriptsIdRouteImport.update({
  id: '/scripts/$id',
  path: '/scripts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrompterIdRoute = PrompterIdRouteImport.update({
  id: '/prompter/$id',
  path: '/prompter/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/prompter/$id': typeof PrompterIdRoute
  '/scripts/$id': typeof ScriptsIdRoute
  '/scripts/new': typeof ScriptsNewRoute
  '/prompter/': typeof PrompterIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/prompter/$id': typeof PrompterIdRoute
  '/scripts/$id': typeof ScriptsIdRoute
  '/scripts/new': typeof ScriptsNewRoute
  '/prompter': typeof PrompterIndexRoute
  '/scripts': typeof ScriptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/prompter/$id': typeof PrompterIdRoute
  '/scripts/$id': typeof ScriptsIdRoute
  '/scripts/new': typeof ScriptsNewRoute
  '/prompter/': typeof PrompterIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/prompter/$id'
    | '/scripts/$id'
    | '/scripts/new'
    | '/prompter/'
    | '/scripts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/prompter/$id'
    | '/scripts/$id'
    | '/scripts/new'
    | '/prompter'
    | '/scripts'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/prompter/$id'
    | '/scripts/$id'
    | '/scripts/new'
    | '/prompter/'
    | '/scripts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  PrompterIdRoute: typeof PrompterIdRoute
  ScriptsIdRoute: typeof ScriptsIdRoute
  ScriptsNewRoute: typeof ScriptsNewRoute
  PrompterIndexRoute: typeof PrompterIndexRoute
  ScriptsIndexRoute: typeof ScriptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof ScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompter/': {
      id: '/prompter/'
      path: '/prompter'
      fullPath: '/prompter/'
      preLoaderRoute: typeof PrompterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/new': {
      id: '/scripts/new'
      path: '/scripts/new'
      fullPath: '/scripts/new'
      preLoaderRoute: typeof ScriptsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$id': {
      id: '/scripts/$id'
      path: '/scripts/$id'
      fullPath: '/scripts/$id'
      preLoaderRoute: typeof ScriptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompter/$id': {
      id: '/prompter/$id'
      path: '/prompter/$id'
      fullPath: '/prompter/$id'
      preLoaderRoute: typeof PrompterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  PrompterIdRoute: PrompterIdRoute,
  ScriptsIdRoute: ScriptsIdRoute,
  ScriptsNewRoute: ScriptsNewRoute,
  PrompterIndexRoute: PrompterIndexRoute,
  ScriptsIndexRoute: ScriptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
